#!/usr/bin/env bash
#
# Regenerates /etc/nginx/conf.d/cloudflare-realip.conf from Cloudflare's published ranges.
# Run as: sudo bash deploy/nginx/cloudflare-realip.sh
#
# Why this exists: with the domain proxied, every request reaches nginx from a Cloudflare
# address. This tells nginx to replace $remote_addr with the value of CF-Connecting-IP, but
# ONLY when the connection genuinely came from Cloudflare. PHP then receives the true client
# IP in REMOTE_ADDR, so Laravel needs to trust nothing beyond 127.0.0.1.
#
# That matters because $request->ip() is the throttle key for the auth rate limiters. Getting
# it wrong collapses every visitor onto one key (see AppServiceProvider::configureTrustedProxies).
#
# Cloudflare changes these ranges occasionally — re-run after a Cloudflare announcement, or
# put it on a monthly cron. It reloads nginx only if the config actually changed.
set -euo pipefail

OUT=/etc/nginx/conf.d/cloudflare-realip.conf
TMP=$(mktemp)

{
  echo "# Generated by deploy/nginx/cloudflare-realip.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Do not edit by hand — re-run the script instead."
  for url in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
    curl -fsS "$url" | while read -r cidr; do
      [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
    done
  done
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > "$TMP"

# Sanity: a truncated fetch must never be installed, or nginx stops trusting Cloudflare
# and every client IP silently becomes a Cloudflare address again.
if [ "$(grep -c set_real_ip_from "$TMP")" -lt 10 ]; then
  echo "Refusing to install: only $(grep -c set_real_ip_from "$TMP") ranges fetched (expected 20+)." >&2
  rm -f "$TMP"; exit 1
fi

if cmp -s "$TMP" "$OUT" 2>/dev/null; then
  echo "Cloudflare ranges unchanged ($(grep -c set_real_ip_from "$TMP") entries)."
  rm -f "$TMP"; exit 0
fi

install -m 0644 "$TMP" "$OUT"; rm -f "$TMP"
nginx -t && systemctl reload nginx
echo "Installed $(grep -c set_real_ip_from "$OUT") Cloudflare ranges and reloaded nginx."
