<div class="flex flex-col gap-4">
    @if($flashMessage)<div class="rounded-lg bg-zinc-100 p-3 text-sm dark:bg-zinc-800">{{ $flashMessage }}</div>@endif
    <div class="flex flex-wrap items-start justify-between gap-3"><div><a href="{{ route('crash-groups.index') }}" class="text-sm text-blue-600">← Crash groups</a><h1 class="mt-1 text-xl font-semibold">{{ $group->name }}</h1><p class="text-sm text-zinc-500">{{ $group->exception_class }} · <span class="font-mono">{{ $group->fingerprint }}</span></p></div><span class="rounded-full bg-zinc-100 px-3 py-1 text-sm dark:bg-zinc-800">{{ ucfirst($group->status->value) }}</span></div>
    <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">@foreach([['Occurrences',$group->occurrence_count],['Affected users',$group->affected_user_count],['First seen',$group->first_seen_at->diffForHumans()],['Last seen',$group->last_seen_at->diffForHumans()],['Fixed version',$group->fixed_app_version ?? '—']] as [$label,$value])<div class="rounded-xl border p-4 dark:border-zinc-700"><div class="text-xs text-zinc-500">{{ $label }}</div><div class="mt-1 font-semibold">{{ $value }}</div></div>@endforeach</div>
    @can('manageTelemetry')<div class="grid gap-2 rounded-xl border p-4 dark:border-zinc-700 md:grid-cols-3"><input wire:model="reason" placeholder="Required action reason" class="rounded-lg border px-3 py-2 text-sm dark:bg-zinc-900"/><input wire:model="fixedVersion" placeholder="Fixed app version" class="rounded-lg border px-3 py-2 text-sm dark:bg-zinc-900"/><div class="text-sm text-zinc-500">Assigned: {{ $group->assignee?->email ?? 'Nobody' }}</div><button wire:click="assignToSelf" class="rounded-lg bg-blue-600 px-3 py-2 text-sm text-white">Assign to me</button><button wire:click="unassign" class="rounded-lg bg-zinc-600 px-3 py-2 text-sm text-white">Unassign</button><button wire:click="changeStatus('investigating')" class="rounded-lg bg-blue-700 px-3 py-2 text-sm text-white">Investigate</button><button wire:click="changeStatus('resolved')" class="rounded-lg bg-green-700 px-3 py-2 text-sm text-white">Resolve</button><button wire:click="changeStatus('ignored')" class="rounded-lg bg-zinc-700 px-3 py-2 text-sm text-white">Ignore</button><button wire:click="changeStatus('open')" class="rounded-lg bg-amber-700 px-3 py-2 text-sm text-white">Reopen</button></div>
    <div class="rounded-xl border p-4 dark:border-zinc-700"><textarea wire:model="note" placeholder="Internal engineering note" class="w-full rounded-lg border p-3 dark:bg-zinc-900"></textarea><button wire:click="addNote" class="mt-2 rounded-lg bg-zinc-800 px-3 py-2 text-sm text-white">Add note</button></div>@endcan
    <div class="grid gap-2 md:grid-cols-3"><input wire:model.live.debounce.300ms="release" placeholder="Filter release" class="rounded-lg border px-3 py-2 text-sm dark:bg-zinc-900"/><input wire:model.live.debounce.300ms="os" placeholder="Filter OS" class="rounded-lg border px-3 py-2 text-sm dark:bg-zinc-900"/><input wire:model.live.debounce.300ms="device" placeholder="Filter device" class="rounded-lg border px-3 py-2 text-sm dark:bg-zinc-900"/></div>
    <div class="rounded-xl border p-4 dark:border-zinc-700"><h2 class="font-semibold">14-day occurrences · {{ $filteredCount }} filtered total</h2>@php($max=max(1,(int)$chart->max('total')))<div class="mt-4 flex h-28 items-end gap-2">@forelse($chart as $day)<div class="flex flex-1 flex-col items-center justify-end gap-1"><span class="text-xs">{{ $day->total }}</span><div class="w-full rounded-t bg-red-500" style="height: {{ max(3,($day->total/$max)*80) }}px"></div><span class="text-[10px] text-zinc-500">{{ \Carbon\Carbon::parse($day->day)->format('M j') }}</span></div>@empty<p class="text-sm text-zinc-500">No occurrences in this window.</p>@endforelse</div></div>
    <div class="rounded-xl border p-4 dark:border-zinc-700"><h2 class="font-semibold">Representative events</h2><div class="mt-3 divide-y dark:divide-zinc-700">@forelse($samples as $event)<div class="flex flex-wrap justify-between gap-2 py-3 text-sm"><a href="{{ route('events.show',$event) }}" class="text-blue-600">Event #{{ $event->id }}</a><span>{{ $event->app_version_name ?? '—' }} · Android {{ $event->os_version ?? '—' }}</span><span>{{ $event->device->manufacturer }} {{ $event->device->model }}</span><span>{{ $event->received_at->diffForHumans() }}</span></div>@empty<p class="py-3 text-sm text-zinc-500">No matching sample events.</p>@endforelse</div></div>
    <div class="rounded-xl border p-4 dark:border-zinc-700"><h2 class="font-semibold">Internal notes</h2>@forelse($group->notes as $note)<div class="mt-3 text-sm"><p>{{ $note->body }}</p><span class="text-xs text-zinc-500">{{ $note->author?->email ?? 'Deleted administrator' }} · {{ $note->created_at->diffForHumans() }}</span></div>@empty<p class="mt-3 text-sm text-zinc-500">No notes yet.</p>@endforelse</div>
</div>
